#image: python:3.9.7
image: eragon1442/conda:ml_bitbucket_1.0


pipelines:
    pull-requests:
        main:
        - step:
                name: testing env
                script:
                    - echo "Loading enviroment env for feature"
                    - conda activate /opt/conda/envs/ml_bitbucket_demo
                    - echo $CONDA_DEFAULT_ENV
        - step:
                name: tests
                script:
                    - conda activate /opt/conda/envs/ml_bitbucket_demo
                    - echo "Running tests"
                    - python -m unittest discover tests/
        - step:
                name: training
                script:
                    - conda activate /opt/conda/envs/ml_bitbucket_demopus
                    - echo "Running preprocess      "
                    - python preprocessing.py
                    - echo "Running train pipeline"
                    - python train.py
    branches:
        main:
            - step:
                    name: testing env
                    script:
                        - echo "Loading enviroment env"
                        - conda activate /opt/conda/envs/ml_bitbucket_demo
                        - echo $CONDA_DEFAULT_ENV
            - step:
                    name: tests
                    script:
                        - conda activate /opt/conda/envs/ml_bitbucket_demo
                        - echo "Running tests"
                        - python -m unittest discover tests/
            - step:
                    name: training
                    script:
                        - conda activate /opt/conda/envs/ml_bitbucket_demopus
                        - echo "Running preprocess pipeline"
                        - python preprocessing.py
                        - echo "Running train pipeline"
                        - python train.py