name: run-pipeline

on: [ pull_request, push]


jobs:
  mlops:
#    runs-on: [self-hosted, linux]
    runs-on: ubuntu-22.04
    container: eragon1442/conda:ml_bitbucket_1.0
    env:
      TO_PRINT: hey
    steps:
      - uses: actions/checkout@v2
      - name: testing env
        run : |
          echo "Loading enviroment env for feature"
          /opt/conda/bin/conda activate /opt/conda/envs/ml_bitbucket_demo
          echo $CONDA_DEFAULT_ENV
          
      - name: tests
        run : |
          echo "Running tests"
          python -m unittest discover tests/

      - name: Training
        run : |
          echo "Running preprocess"
          python preprocessing.py
          echo "Running train pipeline"
          python train.py



  job-1:
#    runs-on: [self-hosted, linux]
    runs-on: ubuntu-22.04
    env:
      TEST_KEY: ${{secrets.secret_key_test}} 
   
    steps:
      - uses: actions/checkout@v2
      - name: Print the secret key
        run : |
          echo "please just as an example"
          echo $TEST_KEY


